name: Build

on: 
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  patch:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@main
      - name: Downloading YouTube
        run: |
          # https://apkpure.com/youtube/com.google.android.youtube/versions
          # YouTube 17.33.42
          $Parameters = @{
              Uri             = "https://apkpure.com/youtube/com.google.android.youtube/download/1531188672-APK-1d33a9dd6b47ec963ea80d2437ef7d3f"
              UseBasicParsing = $true
              Verbose         = $true
          }
          $URL = ((Invoke-Webrequest @Parameters).Links | Where-Object -FilterScript {$_.href -match "https://download.apkpure.com"}).href
          $Parameters = @{
              Uri             = $URL
              Outfile         = "$PSScriptRoot\youtube.apk"
              UseBasicParsing = $true
              Verbose         = $true
          }
          Invoke-Webrequest @Parameters

      - name: Downloading ReVanced CLI
        run: |
          # https://github.com/revanced/revanced-cli
          $Parameters = @{
              Uri             = "https://api.github.com/repos/revanced/revanced-cli/releases/latest"
              UseBasicParsing = $true
              Verbose         = $true
          }
          $Tag = (Invoke-RestMethod @Parameters).tag_name
          $Tag2 = $Tag.replace("v", "")
          $Parameters = @{
              Uri             = "https://github.com/revanced/revanced-cli/releases/download/$Tag/revanced-cli-$Tag2-all.jar"
              Outfile         = "$PSScriptRoot\revanced-cli.jar"
              UseBasicParsing = $true
              Verbose         = $true
          }
          Invoke-RestMethod @Parameters

          (Get-Content -Path Release.md -Encoding utf8).replace("CLITag", $Tag) | Set-Content -Path Release.md -Encoding utf8 -Force

      - name: Downloading ReVanced Patches
        run: |
          # https://github.com/revanced/revanced-patches
          $Parameters = @{
              Uri             = "https://api.github.com/repos/revanced/revanced-patches/releases/latest"
              UseBasicParsing = $true
              Verbose         = $true
          }
          $Tag = (Invoke-RestMethod @Parameters).tag_name
          $Tag2 = $Tag.replace("v", "")
          $Parameters = @{
              Uri             = "https://github.com/revanced/revanced-patches/releases/download/$Tag/revanced-patches-$Tag2.jar"
              Outfile         = "$PSScriptRoot\revanced-patches.jar"
              UseBasicParsing = $true
              Verbose         = $true
          }
          Invoke-RestMethod @Parameters

          (Get-Content -Path Release.md -Encoding utf8).replace("PatchesTag", $Tag) | Set-Content -Path Release.md -Encoding utf8 -Force

      - name: Downloading ReVanced Integrations
        run: |
          # https://github.com/revanced/revanced-integrations
          $Parameters = @{
              Uri             = "https://api.github.com/repos/revanced/revanced-integrations/releases/latest"
              UseBasicParsing = $true
              Verbose         = $true
          }
          $Tag = (Invoke-RestMethod @Parameters).tag_name
          $Parameters = @{
              Uri             = "https://github.com/revanced/revanced-integrations/releases/download/$Tag/app-release-unsigned.apk"
              Outfile         = "$PSScriptRoot\app-release-unsigned.apk"
              UseBasicParsing = $true
              Verbose         = $true
          }
          Invoke-RestMethod @Parameters

          (Get-Content -Path Release.md -Encoding utf8).replace("IntegrationsTag", $Tag) | Set-Content -Path Release.md -Encoding utf8 -Force

      - name: Downloading GmsCore
        run: |
          # https://github.com/microg/GmsCore
          $Parameters = @{
              Uri             = "https://api.github.com/repos/microg/GmsCore/releases/latest"
              UseBasicParsing = $true
              Verbose         = $true
          }
          $URL = ((Invoke-RestMethod @Parameters).assets | Where-Object -FilterScript {$_.browser_download_url -notmatch "asc"}).browser_download_url
          $Parameters = @{
               Uri             = $URL
               Outfile         = "$PSScriptRoot\microg.apk"
               UseBasicParsing = $true
               Verbose         = $true
          }
          Invoke-RestMethod @Parameters

          (Get-Content -Path Release.md -Encoding utf8).replace("GmsCoreTag", $Tag) | Set-Content -Path Release.md -Encoding utf8 -Force

      - name: Downloading latest Zulu JDK
        run: |
          # https://github.com/ScoopInstaller/Java/blob/master/bucket/zulu-jdk.json
          $Parameters = @{
              Uri             = "https://raw.githubusercontent.com/ScoopInstaller/Java/master/bucket/zulu-jdk.json"
              UseBasicParsing = $true
              Verbose         = $true
          }
          $URL = (Invoke-RestMethod @Parameters).architecture."64bit".url
          $Tag = (Invoke-RestMethod @Parameters).version
          $Parameters = @{
              Uri             = $URL
              Outfile         = "$PSScriptRoot\jdk_windows-x64_bin.zip"
              UseBasicParsing = $true
              Verbose         = $true
          }
          Invoke-RestMethod @Parameters

          (Get-Content -Path Release.md -Encoding utf8).replace("ZuluTag", $Tag) | Set-Content -Path Release.md -Encoding utf8 -Force

      - name: Expanding Zulu JDK
        run: |
          # Expand jdk_windows-x64_bin archive
          $Parameters = @{
              Path            = "$PSScriptRoot\jdk_windows-x64_bin.zip"
              DestinationPath = "$PSScriptRoot\jdk_windows-x64_bin"
              Force           = $true
              Verbose         = $true
          }
          Expand-Archive @Parameters

          Remove-Item -Path "$PSScriptRoot\jdk_windows-x64_bin.zip" -Force

      - name: Building
        run: |
          # https://github.com/revanced/revanced-patches
          & "$PSScriptRoot\jdk_windows-x64_bin\zulu*win_x64\bin\java.exe" `
          -jar "$PSScriptRoot\revanced-cli.jar" `
          --apk "$PSScriptRoot\youtube.apk" `
          --bundles "$PSScriptRoot\revanced-patches.jar" `
          --merge "$PSScriptRoot\app-release-unsigned.apk" `
          --exclude timeline-ads `
          --exclude premium-icon-reddit `
          --exclude general-reddit-ads `
          --exclude pflotsh-ecmwf-subscription-unlock `
          --exclude minimized-playback-music --exclude tasteBuilder-remover --exclude hide-get-premium --exclude compact-header --exclude upgrade-button-remover --exclude background-play --exclude music-microg-support --exclude music-video-ads --exclude codecs-unlock --exclude exclusive-audio-playback `
          --exclude promo-code-unlock `
          --exclude tiktok-ads `
          --exclude swipe-controls --exclude downloads --exclude amoled --exclude hide-autoplay-button --exclude premium-heading --exclude disable-fullscreen-panels --exclude old-quality-layout --exclude enable-wide-searchbar --exclude tablet-mini-player --exclude always-autorepeat --exclude enable-debugging --exclude custom-playback-speed --exclude hide-infocard-suggestions `
          --clean `
          --temp-dir "$PSScriptRoot\Temp" `
          --out "$PSScriptRoot\revanced.apk"

      - name: Creating archive
        run: |
          $Parameters = @{
              Path             = "$PSScriptRoot\revanced.apk", "$PSScriptRoot\microg.apk"
              DestinationPath  = "ReVanced.zip"
              CompressionLevel = "Fastest"
              Force            = $true
          }
          Compress-Archive @Parameters

      - name: Release.md
        run: |
          $Release = (Get-Content -Path Release.md -Raw -Encoding utf8).replace("%", "[char]0x25").replace("\n", "[char]0x0A").replace("\r", "[char]0x0D") | Set-Content -Path Release.md -Force
          echo "Release_Body=$Release" >> $env:GITHUB_ENV

      - name: Uploading ReVanced.zip to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ReVanced.zip
          tag: ${{ github.ref }}
          body: ${{ env.Release_Body }}
          overwrite: true
          file_glob: true
          prerelease: $false
