name: Release

on: 
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  patch:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@main

      - name: Release.txt
        id: read_release
        run: |
          $Release = (Get-Content -Path Release.txt -Encoding utf8 -Raw)
          $Release = $Release.replace("%", $([char]0x25))
          $Release = $Release.replace("*", $([char]0x002A))
          $Release = $Release.replace("`n", $([char]0x0A))
          $Release = $Release.replace("`r", $([char]0x0D))

          echo "::set-output name=RELEASE_BODY::$Release"
          ${{ steps.read_release.outputs.RELEASE_BODY }}

      - name: Uploading ReVanced.zip to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Release.txt
          tag: ${{ github.ref }}
          body: ${{ steps.read_release.outputs.RELEASE_BODY }}
          overwrite: true
          file_glob: true
          prerelease: $false
