name: Release

on: 
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  patch:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@main

      - name: Release.txt
        id: read_release
        run: |
          $Release = (Get-Content -Path Release.txt -Encoding utf8 -Raw).replace("%", "[char]0x25").replace("*", "[char]0x002A").replace("\n", "[char]0x0A").replace("\r", "[char]0x0D")
          $Release
          echo "::set-output name=RELEASE_BODY::$Release"
          ${{ steps.read_release.outputs.RELEASE_BODY }}

      - name: Uploading ReVanced.zip to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: ${{ steps.read_release.outputs.RELEASE_BODY }}
          prerelease: $false
