name: Tag and Trigger Build

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to push tags

      - name: Generate date tag and push
        run: |
          TAG=$(date +'%Y.%m.%d')
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Exiting."
            exit 1
          fi

          git tag "$TAG"
          git push origin "$TAG"
